version: '3.2'

services:
  # web:
    # build:
      # context: ./dockers/
      # dockerfile: Dockerfile.web
    # links:
    # - db

    # environment:
    #   TZ: "America/Montreal"
    #   UWSGI_CHEAPER: 0
    #   UWSGI_PROCESSES: 1
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: password
    # cpus: 1.0

  db:
    image: mongo:3-xenial
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
    - ./mongodb:/data/db:rw

  dbmanager:
    image: mongo-express
    links:
    - db
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  # haproxy:
  #   image: dockercloud/haproxy:latest
  #   links:
  #   - web
  #   ports:
  #   - 8086:80
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock

  # iot:
  #   build:
  #     context: ./dockers/
  #     dockerfile: Dockerfile.iot
  #   links:
  #   - haproxy
  #   environment:
  #     TEST_URL: http://haproxy/sensor/add
  #     TZ: "America/Montreal"
  #   volumes:
  #   - ./IoT:/app/run

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - grafana
      - dbmanager
      - prometheus

  grafana:
    image: grafana/grafana:7.3.6
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - db


    
